version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./code:/app/code
    environment:
      MYSQL_HOST: "db" 
      MYSQL_DATABASE: targets
      MYSQL_USER: targets
      MYSQL_PASSWORD: password
      ID: "1234"
    #command: tail -f /etc/fstab
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: targets
      MYSQL_USER: targets
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./seed:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306 